version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
    restart: always
    # 如果需要挂载配置文件或其他文件
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs

  # 如果需要数据库服务，比如 MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      # - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

# 定义持久化卷
volumes:
  mysql-data:
  redis-data: